### ISSUE TITLE
BYG leaf textures change color

### ISSUE THREAD

**Issue by queenizzy** [TeamMidnightDust/BetterLeavesPack#30] opened 2023-02-26 04:51 UTC
So basically the colors are off for the BYG leaf textures, for example cherry blossom forest was green and yellow.  I am using optifine and the mod pack enigmatica 6 for reference. But I don’t think it has anything to do with the pack .

**Comment by Motschen** [comment] 2023-02-26 09:48
This is caused by OptiFine and already known in other issues, so I'm closing this one.

**Closed by Motschen** 2023-02-26 09:48 UTC
